### ISSUE TITLE
Data for Liechtenstein

### ISSUE THREAD

**Issue by lucasrodes** [rsalzer/COVID_19_VACC#4]
Hi, 
First of all, thanks for your project and efforts! I am currently using your data in my project https://github.com/sociepy/covid19-vaccination-subnational, trying to gather regional data at a global scale.

I have noticed that `ncumul_vacc` field contains ups and downs in Liechtenstein data. Is there an error in the source data reports, maybe?

See below:

```python
>>> import pandas as pd
>>> url = "https://github.com/rsalzer/COVID_19_VACC/raw/main/data.csv"
>>> df  = pd.read_csv(url)
>>> df.loc[df["geounit"]=="FL"].sort_values("date")[["date", "ncumul_vacc"]]
           date  ncumul_vacc
28   2021-01-21          306
57   2021-01-24         1155
60   2021-01-27          643
113  2021-01-31          833
```

**Comment by rsalzer** [comment]
Unfortunately it is part of the data ... you can find the original pdf in the archive-folder.
