### ISSUE TITLE
Update with latest 03.02.2021 FOPH json-API data?

### ISSUE THREAD

**Issue by d-qn** [rsalzer/COVID_19_VACC#5]
Hi there,

I am just wondering if the scraper is broken or whether there were changes to FOPH's API. New data with 03.02.2021 timestamp is available on the API since mid-day.

Thanks in advance 🙏

**Comment by rsalzer** [comment]
The scraper failed because they have a double entry for CHFL ... I am adding manually...

**Comment by rsalzer** [comment]
Done manually: https://github.com/rsalzer/COVID_19_VACC/commit/b0024e8b04eca9d929b2bf5d82394dcac39aa7a8

**Comment by d-qn** [comment]
🤦🏼‍♂️Geez... Thanks a lot! I guess manual fix needed for manual data entry

**Comment by rsalzer** [comment]
So ... the scraper is manually at the moment ... till the data is more reliable. So if I am really late with it, please ping me :)
