### ISSUE TITLE
Data fields (fully vaccinated) missing.

### ISSUE THREAD

**Issue by lucasrodes** [rsalzer/COVID_19_VACC#6]
Hi,
I  noticed that the format from data.csv is missing fields `ncumul_fully_vacc` and `ncumul_fully_vacc_per100pop`, mentioned in the [README](../blob/main/README.md)

**Comment by rsalzer** [comment]
Yes... i added them in the readme but havent implemented the scraper yet 🙈

**Comment by rsalzer** [comment]
Ok, its done now.
Please note that fully vaccinated data is only available for the last two recent dates.
https://github.com/rsalzer/COVID_19_VACC/commit/5a49308984362f43cc8dcb20039e01f08dd85d86

**Comment by lucasrodes** [comment]
Thanks for the quick solution @rsalzer
